// <auto-generated />
namespace AddressBookEntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class external_contact_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(external_contact_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201912041535187_external_contact_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
